name: Branch check
on:
  pull_request:
    branches: [master]
  workflow_dispatch:
jobs:
  branch-check:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20.13.1]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Check types
        run: npm run type-check
      - name: Run unit tests
        run: npm run unit-test
      - name: Build
        run: npm run build
